import pandas as pd


def create_payment_dataset():

    data = [
        {
            "transaction_id": "TXN001",
            "customer_id": "CUST001",
            "amount": 1200,
            "payment_method": "UPI",
            "failure_reason": "network_error",
            "attempt_count": 1,
            "previous_success_rate": 0.95,
            "customer_tenure": 24,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN002",
            "customer_id": "CUST002",
            "amount": 2500,
            "payment_method": "CARD",
            "failure_reason": "insufficient_funds",
            "attempt_count": 1,
            "previous_success_rate": 0.80,
            "customer_tenure": 12,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN003",
            "customer_id": "CUST003",
            "amount": 7500,
            "payment_method": "CARD",
            "failure_reason": "card_declined",
            "attempt_count": 2,
            "previous_success_rate": 0.45,
            "customer_tenure": 3,
            "risk_level": "medium",
        },
        {
            "transaction_id": "TXN004",
            "customer_id": "CUST004",
            "amount": 1800,
            "payment_method": "UPI",
            "failure_reason": "network_error",
            "attempt_count": 1,
            "previous_success_rate": 0.92,
            "customer_tenure": 18,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN005",
            "customer_id": "CUST005",
            "amount": 15000,
            "payment_method": "CARD",
            "failure_reason": "card_declined",
            "attempt_count": 3,
            "previous_success_rate": 0.30,
            "customer_tenure": 2,
            "risk_level": "high",
        },
        {
            "transaction_id": "TXN006",
            "customer_id": "CUST006",
            "amount": 3200,
            "payment_method": "NETBANKING",
            "failure_reason": "bank_timeout",
            "attempt_count": 1,
            "previous_success_rate": 0.88,
            "customer_tenure": 30,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN007",
            "customer_id": "CUST007",
            "amount": 4500,
            "payment_method": "UPI",
            "failure_reason": "insufficient_funds",
            "attempt_count": 2,
            "previous_success_rate": 0.70,
            "customer_tenure": 9,
            "risk_level": "medium",
        },
        {
            "transaction_id": "TXN008",
            "customer_id": "CUST008",
            "amount": 900,
            "payment_method": "CARD",
            "failure_reason": "network_error",
            "attempt_count": 1,
            "previous_success_rate": 0.97,
            "customer_tenure": 36,
            "risk_level": "low",
        },

        # Challenging cases

        {
            "transaction_id": "TXN009",
            "customer_id": "CUST009",
            "amount": 6000,
            "payment_method": "UPI",
            "failure_reason": "network_error",
            "attempt_count": 3,
            "previous_success_rate": 0.95,
            "customer_tenure": 20,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN010",
            "customer_id": "CUST010",
            "amount": 8500,
            "payment_method": "CARD",
            "failure_reason": "network_error",
            "attempt_count": 1,
            "previous_success_rate": 0.40,
            "customer_tenure": 4,
            "risk_level": "medium",
        },
        {
            "transaction_id": "TXN011",
            "customer_id": "CUST011",
            "amount": 11000,
            "payment_method": "CARD",
            "failure_reason": "network_error",
            "attempt_count": 1,
            "previous_success_rate": 0.90,
            "customer_tenure": 2,
            "risk_level": "high",
        },
        {
            "transaction_id": "TXN012",
            "customer_id": "CUST012",
            "amount": 2100,
            "payment_method": "NETBANKING",
            "failure_reason": "bank_timeout",
            "attempt_count": 2,
            "previous_success_rate": 0.91,
            "customer_tenure": 15,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN013",
            "customer_id": "CUST013",
            "amount": 5000,
            "payment_method": "CARD",
            "failure_reason": "card_declined",
            "attempt_count": 1,
            "previous_success_rate": 0.85,
            "customer_tenure": 16,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN014",
            "customer_id": "CUST014",
            "amount": 7200,
            "payment_method": "UPI",
            "failure_reason": "insufficient_funds",
            "attempt_count": 1,
            "previous_success_rate": 0.93,
            "customer_tenure": 28,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN015",
            "customer_id": "CUST015",
            "amount": 14000,
            "payment_method": "CARD",
            "failure_reason": "card_declined",
            "attempt_count": 2,
            "previous_success_rate": 0.25,
            "customer_tenure": 1,
            "risk_level": "high",
        },
        {
            "transaction_id": "TXN016",
            "customer_id": "CUST016",
            "amount": 1600,
            "payment_method": "UPI",
            "failure_reason": "bank_timeout",
            "attempt_count": 1,
            "previous_success_rate": 0.86,
            "customer_tenure": 10,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN017",
            "customer_id": "CUST017",
            "amount": 3900,
            "payment_method": "CARD",
            "failure_reason": "unknown_error",
            "attempt_count": 1,
            "previous_success_rate": 0.90,
            "customer_tenure": 22,
            "risk_level": "medium",
        },
        {
            "transaction_id": "TXN018",
            "customer_id": "CUST018",
            "amount": 9500,
            "payment_method": "UPI",
            "failure_reason": "network_error",
            "attempt_count": 2,
            "previous_success_rate": 0.82,
            "customer_tenure": 8,
            "risk_level": "medium",
        },
        {
            "transaction_id": "TXN019",
            "customer_id": "CUST019",
            "amount": 2700,
            "payment_method": "NETBANKING",
            "failure_reason": "bank_timeout",
            "attempt_count": 3,
            "previous_success_rate": 0.96,
            "customer_tenure": 40,
            "risk_level": "low",
        },
        {
            "transaction_id": "TXN020",
            "customer_id": "CUST020",
            "amount": 18000,
            "payment_method": "CARD",
            "failure_reason": "unknown_error",
            "attempt_count": 2,
            "previous_success_rate": 0.35,
            "customer_tenure": 2,
            "risk_level": "high",
        },
    ]

    return pd.DataFrame(data)